# Generated by Django 3.1.3 on 2020-11-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0002_auto_20201120_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
    ]
